notifications:
  email:
    on_success: never
    on_failure: always

sudo: false

language: csharp
Solution: Library.sln

mono: none
dotnet: 2.0.0
dist: trusty

install:
  - cd src/Library.Web.Mvc
  - dotnet restore
  - cd ../..

script:
  - cd test/Library.Tests
  - dotnet test
  - cd ../../

before_deploy:
  - cd build
  - sh build.sh
  - sh build-migrator.sh
  - cd ..
  - zip -r migrator.zip migrator/
  - zip -r dist.zip dist/
  - zip -r sqls.zip sql/

deploy:
  provider: releases
  api_key: "gMrhkkA+SSSY3njsDCJ3U8OrUOADjluYsO4H7N4UtF8lfPE2FRlfZDqbMS0KkeknODCZ28rt9r3q53WOgDzrQG8LDNm51lR0Jg+wDdIi1OclhLWsSlfvO+4ays/iApJTsbpo1FzxO79VwhBw6bPl9ObsUPGprBaQHvknhhxbPYlEHfQDucAAev54bdYmmDwoXzXQOhmDDDvVtxHEG0wvxK5PrWxNmkMzLjqhB0fMJjgoIlLrC8aZrmVjofYtHV9X8oLr0sJ3jTEhsC24FlW29CIqjlVLSkBHm/lv6SJeZp17Kx29IaljQjjuf33sFEu4MjGDxqSDrptg4YHoVBjneZ75OBdTmCPifhIGI0yDjQ5xoBlJ6Ha9JZ3c9iUEa0mG6d6eIYM+0uDNKMta9UjiLoUE6rlt7kw/ikAgIowcORj/hisvt+BVhA5iNerwITgkmOpZkw7smA8tnPntFfKXGFO+Bb2INGz4W04eci8tcq0lsK6vPNqgI1GYFMFH5akI7ilnVCGUwmA1HWjvlrfdvylwpExyWlxtOWjp9XT0p/A5wh5ih1XlvdtPS2FO7Cq+0kS4eJ3LK9O+nLPqUPLEAOMmf039i3q8BET53yOLHNieLttNquUhQNN4BaIPV1PcX5L0Z1iNdXW7wrbGty6HIgk2P6aEg0azn7Udl5sQXfA="
  file:
    - dist.zip
    - sqls.zip
    - migrator.zip
  skip_cleanup: true
  on:
    tags: true
