notifications:
  email:
    on_success: never
    on_failure: always

sudo: false

language: csharp
Solution: Library.sln

mono: none
dotnet: 2.0.0
dist: trusty

install:
  - cd src/Library.Web.Mvc
  - dotnet restore
  - cd ../..

script:
  - cd test/Library.Tests
  - dotnet test
  - cd ../../

before_deploy:
  - cd build
  - sh build.sh
  - sh build-migrator.sh
  - cd ..
  - zip -r migrator.zip migrator/
  - zip -r dist.zip dist/
  - zip -r sqls.zip sql/

deploy:
  provider: releases
  api_key: "ewPlD1GDyqWOCPUPmz+d2OdoiZRZiGzZwepMVkTKjcSlkDr61xLb9II+ZNVUej2a3As0agn2DpjyTenZ2SJUvprIcm3CjrTOth/hsxrLBQTxubLme2+WMs7Se9CymWWQHH0IZHxeDo0/9/5gK8bEI2pjlAcPgYWbCFNZ+cgJpSVBXnpwe4jVA521ynZ3qga2dYojh3QiI+Q65+4lBtMBgSfCCzxstEKL3YFqi6Hqlanpo4jok0Ebc86Q58+iDuz2WiXBX5cuj6i9c5oONpVFQzH0taT8og71rh/l8a7vqqznhsJ58g6I+FruBNHEF6yLpNRMYScVBhykcJ0ohtjbOMyo/nYGppEK+/uhfNG/bngKzvdzqeBQREY71b8Vpbyp92HitPUSSdsWtyiX4vAHmydLWl9i50F1mEDHdw/aF3ANcN8W61wpYKBqGv9QjOd8UJDTYIFKfzYT8BCGvwV9bEG9C4r02Lwq3MqiiQgEsczcFzNrko7VIk+zr1maarIpZ1w32sKF/abEgjZsVcAw9SFTd5ini0reyoU3mD2Bng5ftyU6RAETGzwabY9Q4Yi30RDseRhCvBDSGi811wzQhq2ej1D1B4602dllt67meyZakJWgJV5d2gLpiOPHcFVyBTHBixpSnWDOnV4ZHdVwaJOQDdFOdaml4KlTBkAVrQc="
  file:
    - dist.zip
    - sqls.zip
    - migrator.zip
  skip_cleanup: true
  on:
    tags: true
