notifications:
  email:
    on_success: never
    on_failure: always

sudo: false

language: csharp
Solution: Library.sln

mono: none
dotnet: 2.0.0
dist: trusty

install:
  - cd src/Library.Web.Mvc
  - dotnet restore
  - cd ../..

script:
  - cd test/Library.Tests
  - dotnet test
  - cd ../../

before_deploy:
  - cd build
  - sh build.sh
  - sh build-migrator.sh
  - cd ..
  - zip -r migrator.zip migrator/
  - zip -r dist.zip dist/
  - zip -r sqls.zip sql/

deploy:
  provider: releases
  secure: faWgHZFElCQkCAtUL060/NpkoXAZwpSWgxukE4Ui0mt/7aGAz3QCN1Q7ccKeHcG5MJ7nxgZocGZbgJWWspUO2eF8GXx8pDWPYWtOtVIamk9PfId5jKHQiAmP/TODMZPrXK4NkWfqhlwVovS9FNFZsTyifSfMOiBK+W3vdEUSp5ChWoKNJgASpl1CPyXGpcpqaZ6a55Aop6Z+XV08tCbc898JvSKcPctY80xUDmNTBXDG9aNkv2p0nX1tQaAyAupoAYu1KIG1LMu0Oyz/dt46w3d66TE89ycpVpoeQhoBnGPyRmmA1wW+znVS2nsG7vK65AFybUhpMjEPsFeljKuD4f5KbsQea+1vU8Hq5/LJ7Iy/Jxf1w3ThSDL3/RrF1xkSxkbkUZOSH5gEipuPaLXGC/hqQmgzOZqkN3N8QsTcwoPETr7plYaoJ9yhOQyDDjIcBjHjkL5PO8RWBzk1nJzvNoiDvgc+3jRCih+ldpTydUG7VBcrcjO+ZyhO555nObq+fuoEN6XnS1EWe6RU0tRB5BLo8YnzEa2zjc6pMmn5PaqG+U+5yAEy2aetFxHB1UjDCeD0wkn9ZU/fspufgJ3lbQ9DilCjmnaooKijjwtxePl8sm21AZhLXZjAECCpEtd3PwIF7C14/LLJXPBYyHQ8FAX8ESYj1sddSP9W+r7nfg0=
  file:
    - dist.zip
    - sqls.zip
    - migrator.zip
  skip_cleanup: true
  on:
    tags: true
