notifications:
  email:
    on_success: never
    on_failure: always

sudo: true

language: csharp
Solution: Library.sln

mono: none
dotnet: 2.0.0
dist: trusty

install:
  - sudo apt-get install -y nodejs
  - cd src/Library.Web.Mvc
  - dotnet restore
  - cd wwwroot
  - npm install
  - cd ../../..

script:
  - cd test/Library.Tests
  - dotnet test
  - cd ../../

before_deploy:
  - dotnet publish -f netcoreapp2.0 -c Release src/Library.Web.Mvc
  - zip -r dist.zip src/Library.Web.Mvc/bin/Release/netcoreapp2.0/publish

deploy:
  provider: releases
  api_key: "d041edda1db6dd816936aa3bb3c9320dba492e36"
  file:
    - dist.zip
  skip_cleanup: true
  on:
    tags: true
