notifications:
  email:
    on_success: never
    on_failure: always

sudo: false

language: csharp
Solution: Library.sln

mono: none
dotnet: 2.0.0
dist: trusty

install:
  - cd src/Library.Web.Mvc
  - dotnet restore
  - cd ../..

script:
  - cd test/Library.Tests
  - dotnet test
  - cd ../../

before_deploy:
  - cd build
  - sh build.sh
  - sh build-migrator.sh
  - cd ..
  - zip -r migrator.zip migrator/
  - zip -r dist.zip dist/
  - zip -r sqls.zip sql/

deploy:
  provider: releases
  api_key: "d041edda1db6dd816936aa3bb3c9320dba492e36"
  file:
    - dist.zip
    - sqls.zip
    - migrator.zip
  skip_cleanup: true
  on:
    tags: true
